map <CR> :w<CR>
set tabstop=4  "4 space tabs
set shiftwidth=4  "4 space shift
set softtabstop=4  "Tab spaces in no hard tab mode
set expandtab  " Expand tabs into spaces
set autoindent  "autoindent on new lines
set nu
set rnu
colorscheme desert
filetype plugin indent on
syntax on

set incsearch  "Start searching immediately
set ignorecase  "Search ignoring case
set smartcase  "Search using smartcase
set scrolloff=5  "Never scroll off
set t_Co=256 "256 color
set encoding=utf-8 "UTF-8 character encoding
set showmatch  "Highlight matching braces
set equalalways  "Split windows equal size
set title  "Set window title to file
set hlsearch  "Highlight on search
set wildmode=longest,list  "Better unix-like tab completion
set clipboard=unnamed  "Copy and paste from system clipboard
set lazyredraw  "Don't redraw while running macros (faster)
" set autochdir  "Change directory to currently open file
set nocompatible  "Kill vi-compatibility
set wrap  "Visually wrap lines
set linebreak  "Only wrap on 'good' characters for wrapping
set backspace=indent,eol,start  "Better backspacing
set linebreak  "Intelligently wrap long files
set ttyfast  "Speed up vim
set nostartofline "Vertical movement preserves horizontal position

" Better comments
set formatoptions+=croqj
set formatoptions-=t
